<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>Lorem.</th>
				<th>Repudiandae.</th>
				<th>Recusandae.</th>
				<th>Repellendus?</th>
				<th>Cupiditate?</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Lorem.</td>
				<td>Distinctio.</td>
				<td>Ducimus.</td>
				<td>Quas.</td>
				<td>Sunt.</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Quod.</td>
				<td>Vel.</td>
				<td>Recusandae.</td>
				<td>Voluptate?</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Esse!</td>
				<td>Ratione?</td>
				<td>Obcaecati?</td>
				<td>Unde.</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Non!</td>
				<td>Nihil.</td>
				<td>Nesciunt!</td>
				<td>Aliquid!</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Laudantium.</td>
				<td>Nihil?</td>
				<td>Incidunt.</td>
				<td>Accusantium.</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Fugit.</td>
				<td>Esse.</td>
				<td>Eaque!</td>
				<td>Itaque.</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Voluptatum.</td>
				<td>Deserunt!</td>
				<td>Dolore!</td>
				<td>Voluptatem.</td>
			</tr>
			<tr>
				<td>Lorem.</td>
				<td>Quasi!</td>
				<td>Impedit!</td>
				<td>Eum.</td>
				<td>Nihil.</td>
			</tr>
		</tbody>
	</table>
</body>
</html>