TRUNCATE TABLE guru;

INSERT INTO guru (nama, kode, nip) VALUES 
("AM", 	"Abdullah Manaf, ST.", ""),
("AJ", 	"Aznur Johan, S.HI.", ""),
("BR", 	"Baidhawi Razi, Bcl.", ""),
("DI", 	"Devi Intan Purnawan, Lc.", ""),
("DF", 	"Dewi Febrianti, M.Pd.", ""),
("ES", 	"Edi Saputra, Lc., MA.", ""),
("EF", 	"Erida Fitri, M.A.(TESOL).", ""),
("FD", 	"Fadhil Ahmadi, M.Ed.", ""),
("FI", 	"Fauzul Ihsan, S.HI.", ""),
("GA", 	"Gamal Akhyar, Lc.", ""),
("HD", 	"Hanif Dahlan, Lc. MA.", ""),
("IA", 	"Ikhsan Amiruddin, S.Pd.I.", ""),
("AH", 	"Ilham Hidayatullah, Lc., MA.", ""),
("IV", 	"Ivan Aulia, Lc.", ""),
("KH", 	"Khairul Hanif, S.Pd.", ""),
("MW", 	"Mawardi Slamat Harianto, M.Pd.", ""),
("MN", 	"Mizani Nurdin, MA.", ""),
("MY", 	"Muhammad Yasin, Lc.", ""),
("MD", 	"Mulyadi Dahlan, Bcl.", ""),
("MQ", 	"Muttaqin Anas, Lc., MA.", ""),
("NS", 	"Nanda Silvia, S.Kep.", ""),
("NL", 	"Nurul Latifa, S.Pd.", ""),
("RH", 	"Rahmadi, Lc.", ""),
("RR", 	"Raidi Rizki Anshari, Bcl.", ""),
("SM", 	"Sulfia Maulidar, S.Pd.", ""),
("SY", 	"Syafruddin, Lc.", ""),
("WS", 	"Wahyu Saputra, S.Pd.I.", ""),
("WH", 	"Wahyuddin, Lc., M.Sh.", ""),
("ZB", 	"Zahrul Bawadi, Lc., MA.", ""),
("XYZ", 	"NEXT TSANAWIYAH", ""),
("AS", 	"Ade Sarwan, Lc.", ""),
("AA", 	"Ahmad Arief M, S.Pd.", ""),
("BR", 	"Baidhawi Razi, Lc.", ""),
("CP", 	"Cut Putri Ainun Jariya", ""),
("MI", 	"dr. Muhammad Ilham", ""),
("EE", 	"Elly Elvina, S. Pd.I.", ""),
("FS", 	"Faisal Ibnu Hajar, S.S.", ""),
("AL", 	"Fatayathul Alim, S. Pd.I.", ""),
("FI", 	"Fauzul Ihsan, S. HI.", ""),
("FA", 	"Fery Adriansyah, Lc.", ""),
("FP", 	"Firdaus Putra, MA.", ""),
("FR", 	"Fitra Ramadhani, Lc.", ""),
("FQ", 	"Furqan Ar-Rasyid, Lc.", ""),
("HY", 	"Hayaturriza, S.Pd.I.", ""),
("IR", 	"Isra Rizki Muntari, S.I.", ""),
("IS", 	"Ista'ana, S. Pd.", ""),
("IT", 	"Istiqamah, Lc.", ""),
("MF", 	"M. Fakhrurrazi, Lc.", ""),
("MU", 	"Munandar", ""),
("MM", 	"Murni Mustari, S.Pd.", ""),
("MJ", 	"Murtadha MJ, Lc.", ""),
("ND", 	"Nanda Elian Sari, S.Pd.", ""),
("AF", 	"Nur Afnidar, S.Pd.", ""),
("NE", 	"Nur Eliani, S.Pd.", ""),
("NM", 	"Nur Masyitah", ""),
("NN", 	"Nur Novianti", ""),
("RR", 	"Raidi Rizki Anshari, Lc.", ""),
("RS", 	"Risa Khairiah", ""),
("RW", 	"Risna Wardani", ""),
("SF", 	"Safrina, S.Pd.I.", ""),
("SD", 	"Shafiatuddiyanah", ""),
("SA", 	"Siti Aisyah", ""),
("UK", 	"Ulfa Khaira", ""),
("UJ", 	"Uzlifatul Jannah, S.S.", ""),
("WS", 	"Wahyu Saputra, S.Pd.", ""),
("WH", 	"Wahyuddin, Lc. M.Sh.", ""),
("WN", 	"Wahyun Nas, S. Pd.I.", ""),
("ZD", 	"Zainuddin", ""),
("ZK", 	"Zikrina", ""),
("FL", 	"Muhammad Fadhil, Lc.", ""),
("L", 	"Linda", ""),
("NO", 	"Novan Satria, S. Sy", ""),
("TI", 	"Teuku Iqhwana. S. Pd", ""),
("ZS", 	"Ziaus Shabri, Lc.", ""),
("MR", 	"Muhammad Rizal, Lc.", ""),
("SAB", 	"Syukran Abu Bakar", ""),
("FSR", 	"Ferra Sri Rizki", "");
